name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-image:

    runs-on: ubuntu-latest

    env:
      GITHUB_REF_NAME: $GITHUB_REF_NAME

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_USERNAME }}/netbox-docker-plugins:$GITHUB_REF_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/netbox-docker-plugins:latest,${{ vars.DOCKERHUB_USERNAME }}/netbox-docker-plugins:${{ env.GITHUB_REF_NAME }}
