name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/netbox-docker-plugins:${{ github.event.release.tag_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKERHUB_USERNAME/netbox-docker-plugins:latest,$DOCKERHUB_USERNAME/netbox-docker-plugins:${{ github.event.release.tag_name }}
